# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blocks.Block')),
                ('has_controls', models.BooleanField(default=True, help_text='If true, adds the previous and next controls', verbose_name='With controls')),
                ('has_indicators', models.BooleanField(default=True, help_text='If true, adds indicators to the carousel', verbose_name='With indicators')),
                ('has_captions', models.BooleanField(default=True, help_text='If true, adds captions to the carousel', verbose_name='With captions')),
                ('interval', models.IntegerField(default=5000, help_text='The amount of time to delay between automatically cycling an item. If false, carousel will not automatically cycle.')),
                ('keyboard', models.BooleanField(default=True, help_text='Whether the carousel should react to keyboard events.')),
                ('pause', models.BooleanField(default=True, help_text='If set to "True", pauses the cycling of the carousel on mouseenter \n            and resumes the cycling of the carousel on mouseleave.\n            If set to "False", hovering over the carousel won\'t pause it.')),
                ('ride', models.BooleanField(default=False, help_text='Autoplays the carousel after the user manually cycles the first item. If "True", autoplays the carousel on load.')),
                ('wrap', models.BooleanField(default=True, help_text='Whether the carousel should cycle continuously or have hard stops.')),
                ('crop_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Crop size')),
                ('image_css_class', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Image css class')),
                ('caption_css_class', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Caption css class')),
            ],
            options={
                'verbose_name': 'Carousel Block',
                'verbose_name_plural': 'Carousel Blocks',
                'manager_inheritance_from_future': True,
            },
            bases=('blocks.block',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='blocks/carousels', verbose_name='Image')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='blocks.Carousel')),
            ],
            options={
                'verbose_name': 'Carousel Block Slide',
                'verbose_name_plural': 'Carousel Block Slides',
            },
        ),
    ]
